### ISSUE TITLE
MacにVagrantをインストールしてCentOS7を使えるように

### ISSUE THREAD

**Issue by RVIRUS0817** [kazuki-sumi/menta#1]
## 要件

まずはLinux環境が必要なのでVagrantをインストールしてください。

## 参考
https://qiita.com/sudachi808/items/3614fd90f9025973de4b

**Comment by kazuki-sumi** [comment]
## VirtualBoxとは
仮想化ソフトの一つです。ハードウェア(CPUやメモリ、ストレージ)を論理的に分割し、別のOSを動かすことができます。コンピュータの中に別のコンピュータを作り動かすイメージで、例えば、OSがWindowsのパソコンを仮想化ソフトを使うことで、OSXを動かしたりできる。

### ホストOS型の仮想化
VirtualBoxはホストOS型仮想化ソフトの種類の一つ。自分が使っているコンピュータのOSをホストOSといい、仮想化ソフトをインストールすることで、ホストOS上で別のOS(ゲストOS)を動作させる仮想技術。ホストOS＋ゲストOSも動かすためハードウェアのリソース消費が大きい。

![ホストOS型.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/308896/755a5aab-bf12-258e-b4a2-38f5d4f430ce.png)


### ハイパーバイザ型の仮想化
直接インストールした仮想化ソフトウェア上で、仮想マシンを動作させるものなので、ホストOS型と違い、ホストOSやゲストOSの概念がありません。そのためリソースの消費量が軽くなるのが特徴です。

![ハイパーバイザ型.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/308896/b32cad4e-b3a8-b0ff-f659-c4ef3920324d.png)

## Vagrantとは
VirtualBoxやVMwareを使用した仮想環境の構築や共有を簡単にできるようにしてくれるツールです。Vagrantfileという仮想化環境の構成情報を記したファイルを元に構築する。ファイルとして保管できるのでチーム内で環境の共有ができ、コマンドで破棄＆再構築も簡単にできる。

**Comment by kazuki-sumi** [comment]
CentOS7起動できました
