### ISSUE TITLE
ログ修正を行う

### ISSUE THREAD

**Issue by RVIRUS0817** [kazuki-sumi/menta#6]
## 要件

以下のように100行あるファイルがある。
下記のように正規表現で自動的に変更してほしい。

[test.log](https://github.com/kazuki-sumi/menta/files/3999185/test.log)

```
INSERT INTO menta_user (user_id, login_date) VALUES (00, '2019-12-25 18:31:38');
INSERT INTO menta_user (user_id, login_date) VALUES (00, '2019-12-25 18:31:38');
INSERT INTO menta_user (user_id, login_date) VALUES (00, '2019-12-25 18:31:38');
INSERT INTO menta_user (user_id, login_date) VALUES (00, '2019-12-25 18:31:38');
x 100
```

**Comment by kazuki-sumi** [comment]
以下にコマンドを記述
sed -i -e "s/^00.*8$/INSERT INTO menta_user (user_id, login_date) VALUES (00, '2019-12-25 18:31:38');/g" ファイルpath
上記コマンドを実行すると「00, '2019-12-25 18:31:38'」が下記のようになる

INSERT INTO menta_user (user_id, login_date) VALUES (00, '2019-12-25 18:31:38');
